# Generated by Django 4.1.2 on 2023-01-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brand_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock_quantity',
        ),
    ]
