# Generated by Django 4.1.2 on 2023-01-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_quantity_product_stock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='discounted_price',
        ),
    ]
